### ISSUE TITLE
注释中的一点小疑问

### ISSUE THREAD

**Issue by MeaninglessAI** [AsuradaYuci/understand_videobased_reid#2]
在ResNet.py文件中，有如下注释：

![wx20190304-144115](https://user-images.githubusercontent.com/23152242/53715077-a4eecb00-3e8b-11e9-9491-24bfafaeb3b0.png)

我阅读过代码后，觉得这个传入的x维度应该是[batch_size,seq_len,channels,height,width] 
这样的话，下面这句代码才合理：
x = x.view(b*t, x.size(2), x.size(3), x.size(4)) 
否则，没有理由将x resize成b*t，batch_size*channels，很莫名其妙

**Comment by AsuradaYuci** [comment]
@yangjinray 你是对的，我当时理解有问题。。

**Comment by MeaninglessAI** [comment]
感谢解答

**Comment by AsuradaYuci** [comment]
@yangjinray 也感谢你指出错误 :smile:
