### ISSUE TITLE
关于 Mars 数据集 在测试阶段的疑惑

### ISSUE THREAD

**Issue by swg209** [AsuradaYuci/understand_videobased_reid#3]
你好，我想问一下，在main文件中设定50个epoch进行一次test，  是相当于使用了整个测试集的数据了吗？  在训练完成后，进行测试的时候，测试的数据集用还是用原来的query_idx 吗？  谢谢

**Comment by AsuradaYuci** [comment]
@swg209 抱歉回复地较晚。1.在main文件中设定50个epoch进行一次test， 是相当于使用了整个测试集的数据。2.其实只要调用了test，用的都是query_idx作为query（同一个测试集），只是训练完成后，我们采用训练得到的最好模型在测试集上进行测试。
