### ISSUE TITLE
如何把验证时候的图片用转化成visdom.images的输入格式？

### ISSUE THREAD

**Issue by swg209** [AsuradaYuci/understand_videobased_reid#4]
你好，我自己制作了一个测试集，但是在测试的时候，imgs 的shape 为（26 , 4 , 3 , 224 , 112)，而visdom.images要求输入为（channel， height，weight） 请问可以怎么转换？  谢谢。

**Comment by AsuradaYuci** [comment]
@swg209 可否贴一下相关代码，不是很理解您的要求。

**Comment by swg209** [comment]
`def test(model, queryloader, galleryloader, pool, use_gpu, ranks=[1, 5, 10, 20]):

    model.eval()  # 模型的评估

    qf, q_pids, q_camids = [], [], []
    for batch_idx, (**imgs**, pids, camids) in enumerate(queryloader):
        if use_gpu:
            imgs = imgs.cuda()
        imgs = Variable(imgs, volatile=True)  # 将imgs装进Variable中,
        # volatile=True的节点不会求导，即使requires_grad=True，也不会进行反向传播，对于不需要反向传播的情景(inference，测试推断)，
        # 该参数可以实现一定速度的提升，并节省一半的显存，因为其不需要保存梯度

        b, n, s, c, h, w = imgs.size()  # b=1, n=视频片段的数目, s=16
        assert(b == 1)  # 断言函数
        imgs = imgs.view(b*n, s, c, h, w)
        features = model(imgs)  # 喂给模型图片，获得特征`

你好，首先非常感谢你的回复。 我想要实现的是在测试的时候可以把输入的图片可视化出来，visdom的图片可视化输入是（channel, height, width） ，而上面代码输入的imgs 是一个6维的张量，想问一下有什么办法可以直接从imgs 获取 到 图片的信息吗？

**Comment by AsuradaYuci** [comment]
@swg209 你可以调整imgs的形状
![Screenshot from 2019-03-29 11:03:36](https://user-images.githubusercontent.com/37969455/55206696-617d4780-5212-11e9-9e2b-adfc5b64e2ef.png)
这样可以得到一张图片，imgsi的形状为c，h，w

**Comment by swg209** [comment]
@AsuradaYuci   可以了 ，谢谢你的帮助。

**Comment by AsuradaYuci** [comment]
@swg209 :smiley_cat:
