### ISSUE TITLE
About train the model

### ISSUE THREAD

**Issue by liuzheng081** [AsuradaYuci/understand_videobased_reid#8]
Hi, I learn from you project, and I can see the steps is:
1-----> I download the Mars data, 
2-----> run the main_video_person_reid.py with pre_trained model----resnet-50-kinetic.pth
3-----> get the trained model to run test.py
of course change some path in the code.

Am I right?

**Comment by AsuradaYuci** [comment]
@liuzheng081 yes，and 'resnet-50-kinetic.pth' is used for resnet3d network.
