### ISSUE TITLE
About the train

### ISSUE THREAD

**Issue by liuzheng081** [AsuradaYuci/understand_videobased_reid#9]
Hi, when i run the main_video_person_reid.py  at the Epoch 50 steps run test. I got an error --------> AttributeError: 'tuple' object has no attribute 'view'  at the code features = features.view(n, -1).
Can you tell me how to fix this error.
Thank you

**Comment by AsuradaYuci** [comment]
@liuzheng081 That means  ‘features = model(imgs)’ return a tuple object. But on 'test' mode, the model should return a vector 'f' according to the code in 'resnet.py'.       
 if not self.training:
         return f
Have you changed the code somewhere?

**Comment by AsuradaYuci** [comment]
@liuzheng081 If you use resnet3d.py, you should change the code in 'forward' function(just like resnet.py).

**Comment by liuzheng081** [comment]
> @liuzheng081 If you use resnet3d.py, you should change the code in 'forward' function(just like resnet.py).

Thank you  I will try that
